MODEL = "ollama/llama3"
NAME = "greeting_agent"
DESCRIPTION = "Agent powered by ollama using Google ADk"
INSTRUCTION = "You are a friendly greeting agent. Respond in brief and cheerful manner."

TITLE = "ADK ollama Agent"
DESCRIPTION_MAIN = "A FastApi server"
VERSION = "1.0.0"
USER_ID = "default_app"
APP_NAME = "greeting_app"
FINAL_RESPONSE = "No response from agent"