name: Deploy MkDocs

on:
  push:
    branches:
      - docs/CT2   # Trigger on pushes to main branch
    paths:
      - '**.md'           # Trigger if any markdown file changes
      - 'docs/**'         # Or any docs folder changes
      - 'mkdocs.yml'      # Or changes to mkdocs config
      - '.github/workflows/doc_deploy.yml'  # Or changes to this workflow file

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          key: ${{ github.ref }}
          path: .cache

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs mkdocs-material
          pip install mkdocs
          pip install pymdown-extensions 

      - name: Build MkDocs site
        run: mkdocs build
      
      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./site

      - name: Publish Pages
        id: deployment
        uses: actions/deploy-pages@v4

      # - name: Deploy to GitHub Pages
      #   uses: peaceiris/actions-gh-pages@v4
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     publish_dir: ./site
